config/routes.rb
Rails.application.routes.draw do
  get 'cars/index'
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :cars do
    resources :bookings, only: [:new, :create]
    resources :car_reviews, only: [:new, :create]
  end

  resources :bookings, only: [:index] do
    resources :payments, only: :new
  end

  post "bookings", to: 'bookings#payment', as: :payments
  get "bookings/success", to: 'bookings#success', as: :booking_success

  get "accept_requests/:booking_id", to: "requests#accept", as: :accept_request
  get "reject_requests/:booking_id", to: "requests#reject", as: :reject_request

  get "users/:user_id", to: 'users#index'
  get "users/:user_id/renter_reviews", to: 'renter_reviews#index'

  post "favorites", to: 'favorites#create', as: :favorites
  delete "favorites/:car_id", to: 'favorites#destroy', as: :favorite

end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :car
  belongs_to :user

  validates :start_date, presence: true
  validates :end_date, presence: true
  # validate :end_date_after_start_date?


  def price
    return (end_date - start_date) / (60*60*24) * car.price_cents
  end

  # private

  # def end_date_after_start_date?
  #   if end_date < start_date
  #     errors.add :end_date, "must be after start date"
  #   end
  # end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @booking = Booking.all
    @requests = Booking.joins(:car).where("cars.owner_id = #{current_user.id} and bookings.status = 'pending'")
    @accepted = Booking.joins(:car).where("cars.owner_id = #{current_user.id} and bookings.status = 'accepted'")
    @rejected = Booking.joins(:car).where("cars.owner_id = #{current_user.id} and bookings.status = 'rejected'")
    @request_count = @requests.count
    @accept_count = @accepted.count
    @reject_count = @rejected.count
  end

  def new
    @booking = Booking.new
  end

  def create
    @car= Car.find(params[:car_id])
    @booking = Booking.new(booking_params)
    @booking.car = @car
    @booking.user_id = current_user.id
    @booking.status = "pending"

    if @booking.save
      session = Stripe::Checkout::Session.create(
        payment_method_types: ['card'],
        line_items: [{
          name: @booking.car.license_plate,
          amount: @booking.price.to_i,
          currency: 'sgd',
          quantity: 1
        }],
        success_url: booking_success_url,
        cancel_url: booking_success_url
      )

      @session = session.id

      render "bookings/order"
    else
      render "cars/show"
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :status)
  end
end

app/views/bookings/index.html.erb
<div class="card container">

<h2 id="tag-title">You have <%= @request_count %> requests awaiting review </h1>

<div class="row">
  <% @requests.each do |request| %>
    <div class="col-3">
      <div class="car-card">
        <div class="car-card-image" style="background-image: url('<%= request.car.image_urls %>')"></div>
        <div class="car-card-content">
          <div class="car-card-content-left">
            <p><%= request.car.brand %></p>
            <p><%= request.car.license_plate %></p>
            <p><%= request.user.name %></p>
            <p>From <%= request.start_date.to_date %> to <%= request.end_date.to_date %></p>
            <p>
              <%= link_to 'Accept', accept_request_path(:booking_id => request.id), class: 'btn btn-outline-secondary' %> 
              <%= link_to 'Reject', reject_request_path(:booking_id => request.id), class: 'btn btn-outline-secondary' %>
            </p>
          </div>
          <div class="car-type"><p><%= request.car.model %></p></div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<h2 id="tag-title">You have accepted <%= @accept_count %> bookings</h2>

<div class="row">
  <% @accepted.each do |accept| %>
    <div class="col-3">
      <div class="car-card">
        <div class="car-card-image" style="background-image: url('<%= accept.car.image_urls %>')"></div>
        <div class="car-card-content">
          <div class="car-card-content-left">
            <p><%= accept.car.brand %></p>
            <p><%= accept.car.license_plate %></p>
            <p><%= accept.user.name %></p>
            <p>From <%= accept.start_date.to_date %> to <%= accept.end_date.to_date %></p>
          </div>
          <div class="car-type"><p><%= accept.car.model %></p></div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<h2 id="tag-title">You have rejected <%= @reject_count %> bookings</h2>

<div class="row">
  <% @rejected.each do |reject| %>
    <div class="col-3">
      <div class="car-card">
        <div class="car-card-image" style="background-image: url('<%= reject.car.image_urls %>')"></div>
        <div class="car-card-content">
          <div class="car-card-content-left">
            <p><%= reject.car.brand %></p>
            <p><%= reject.car.license_plate %></p>
            <p><%= reject.user.name %></p>
            <p>From <%= reject.start_date.to_date %> to <%= reject.end_date.to_date %></p>
          </div>
          <div class="car-type"><p><%= reject.car.model %></p></div>
        </div>
      </div>
    </div>
  <% end %>
</div>
</div>

app/views/bookings/new.html.erb
<h1>Your booking has been created!</h1>

<%= link_to "Back to main", cars_path, class: 'btn btn-primary ml-2' %>

app/views/bookings/order.html.erb
<div class="map" style="background-image: url('<%= @car.image_urls %>')"></div>

<div class="row">
  <div class="col-8">
    <div class="car-show-card">

      <h4 class="car-card-title">Booking confirmation</h4>
      <%= form_tag payments_path do %>

        Car Model: <%= @car.model %>
        <br>
        Car Brand: <%= @car.brand %>
        <br>
        Booking Start: <%= @booking.start_date.strftime("%F")%>
        <br>
        Booking End: <%= @booking.end_date.strftime("%F") %>
        <br>
        Price: $<%= (@booking.price)/100 %>
        <%= hidden_field_tag 'booking_id', @booking.id %>
        <br>
      <% end %>

      Purchase of <strong><%= @booking.car.model %><%= @booking.car.brand %></strong> for <strong><%= humanized_money_with_symbol @booking.price / 100%></strong>
      <br>
      <button id="pay" class="btn btn-secondary">Pay</button>

      <script src="https://js.stripe.com/v3/"></script>
      <script>
        const paymentButton = document.getElementById('pay');
        paymentButton.addEventListener('click', () => {
          const stripe = Stripe('<%= ENV['STRIPE_PUBLISHABLE_KEY'] %>');
          stripe.redirectToCheckout({
            sessionId: '<%= @session %>'
          });
        });
      </script>

    </div>

  </div>

  <div class="col-4">


    <div class="car-show-card">
        <h4 class="car-card-title">Share</h4>
          <i class="fab fa-facebook-square fa-2x"></i>
          <i class="fab fa-twitter-square fa-2x"></i>
          <i class="fab fa-pinterest-square fa-2x"></i>
          <i class="fas fa-envelope-square fa-2x"></i>

    </div>
  </div>
</div>



<br>


<!--
<%= link_to 'Edit', edit_car_path(@car), class: 'btn btn-outline-secondary' %>
<%= link_to 'Back', cars_path, class: 'btn btn-outline-secondary' %>

-->

app/views/bookings/success.html.erb
<h1>Your booking has been created!</h1>

<%= link_to "Back to main", cars_path, class: 'btn btn-primary ml-2' %>