config/routes.rb
Rails.application.routes.draw do
  get 'cars/index'
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :cars do
    resources :bookings, only: [:new, :create]
    resources :car_reviews, only: [:new, :create]
  end

  resources :bookings, only: [:index] do
    resources :payments, only: :new
  end

  post "bookings", to: 'bookings#payment', as: :payments
  get "bookings/success", to: 'bookings#success', as: :booking_success

  get "accept_requests/:booking_id", to: "requests#accept", as: :accept_request
  get "reject_requests/:booking_id", to: "requests#reject", as: :reject_request

  get "users/:user_id", to: 'users#index'
  get "users/:user_id/renter_reviews", to: 'renter_reviews#index'

  post "favorites", to: 'favorites#create', as: :favorites
  delete "favorites/:car_id", to: 'favorites#destroy', as: :favorite

end

app/models/user.rb
class User < ApplicationRecord
  has_many :car_reviews, dependent: :delete_all
  has_many :renter, class_name: "RenterReview"
  has_many :reviewer, class_name: "RenterReview"
  has_many :bookings, dependent: :delete_all
  has_many :favorites, dependent: :delete_all
  has_many :cars, through: :bookings
  has_many :favorite_cars, through: :favorites, class_name: "Car"
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @favorites = Favorite.where(user_id: params[:user_id])
    @car_reviews = CarReview.where(user_id: params[:user_id])
    @confirmed = Booking.all.where("user_id = #{current_user.id} and bookings.status = 'accepted'")
    @declined = Booking.all.where("user_id = #{current_user.id} and bookings.status = 'rejected'")
  end

end

app/views/users/index.html.erb
<div class="card container">

<h2>My Favorite Cars</h1>

<% @favorites.each do |favorite| %>

ID: <%= favorite.id %>
License Plate: <%= favorite.car.license_plate %>
Model: <%= favorite.car.model %>

<%= link_to "Delete", favorite_path(favorite.car_id), method: :delete, class: "btn btn-danger", data: { confirm: "Are you sure?" } %>

<br>

<% end %>

<h2>My Reviews</h1>

<% @car_reviews.each do |car_review| %>


<%=

car_review.review %> : <%=car_review.created_at %>
<br>

<% end %>

<h2 id="tag-title">My Confirmed Bookings (<%= @confirmed.count %>)</h2>

<div class="row">
  <% @confirmed.each do |confirm| %>
    <div class="col-3">
      <div class="car-card">
        <div class="car-card-image" style="background-image: url('<%= confirm.car.image_urls %>')"></div>
        <div class="car-card-content">
          <div class="car-card-content-left">
            <p><%= confirm.car.brand %></p>
            <p><%= confirm.car.license_plate %></p>
            <p><%= confirm.user.name %></p>
            <p>From <%= confirm.start_date.to_date %> to <%= confirm.end_date.to_date %></p>
          </div>
          <div class="car-type"><p><%= confirm.car.model %></p></div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<h2 id="tag-title">My Declined Bookings (<%= @declined.count %>)</h2>

<div class="row">
  <% @declined.each do |decline| %>
    <div class="col-3">
      <div class="car-card">
        <div class="car-card-image" style="background-image: url('<%= decline.car.image_urls %>')"></div>
        <div class="car-card-content">
          <div class="car-card-content-left">
            <p><%= decline.car.brand %></p>
            <p><%= decline.car.license_plate %></p>
            <p><%= decline.user.name %></p>
            <p>From <%= decline.start_date.to_date %> to <%= decline.end_date.to_date %></p>
          </div>
          <div class="car-type"><p><%= decline.car.model %></p></div>
        </div>
      </div>
    </div>
  <% end %>
</div>


<h2>What Others Say About Me</h1>

</div>