config/routes.rb
Rails.application.routes.draw do
  get 'cars/index'
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :cars do
    resources :bookings, only: [:new, :create]
    resources :car_reviews, only: [:new, :create]
  end

  resources :bookings, only: [:index] do
    resources :payments, only: :new
  end

  post "bookings", to: 'bookings#payment', as: :payments
  get "bookings/success", to: 'bookings#success', as: :booking_success

  get "accept_requests/:booking_id", to: "requests#accept", as: :accept_request
  get "reject_requests/:booking_id", to: "requests#reject", as: :reject_request

  get "users/:user_id", to: 'users#index'
  get "users/:user_id/renter_reviews", to: 'renter_reviews#index'

  post "favorites", to: 'favorites#create', as: :favorites
  delete "favorites/:car_id", to: 'favorites#destroy', as: :favorite

end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">

  <%= link_to "#", class: "navbar-brand" do %>

    <%= image_tag "https://img.icons8.com/pastel-glyph/2x/car--v2.png" %>
    <span id="title-text"> Nevcar </span>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "/cars", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Profile", "/users/#{current_user.id}", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'List my car', new_car_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Bookings', bookings_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>