config/routes.rb
Rails.application.routes.draw do
  get 'cars/index'
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :cars do
    resources :bookings, only: [:new, :create]
    resources :car_reviews, only: [:new, :create]
  end

  resources :bookings, only: [:index] do
    resources :payments, only: :new
  end

  post "bookings", to: 'bookings#payment', as: :payments
  get "bookings/success", to: 'bookings#success', as: :booking_success

  get "accept_requests/:booking_id", to: "requests#accept", as: :accept_request
  get "reject_requests/:booking_id", to: "requests#reject", as: :reject_request

  get "users/:user_id", to: 'users#index'
  get "users/:user_id/renter_reviews", to: 'renter_reviews#index'

  post "favorites", to: 'favorites#create', as: :favorites
  delete "favorites/:car_id", to: 'favorites#destroy', as: :favorite

end

app/models/car.rb
class Car < ApplicationRecord
  has_many :car_reviews, dependent: :delete_all
  has_many :renter_reviews, dependent: :delete_all
  has_many :bookings, dependent: :delete_all
  has_many :favorites, dependent: :delete_all
  has_many :users, through: :bookings
  has_many :users_favorite, through: :favorites, source: :user, class_name: "User"
  belongs_to :owner, class_name: "User"

  validates :license_plate, presence: true, uniqueness: true
  validates :age, numericality: { greater_than_or_equal_to: 0 }
  validates :brand, presence: true
  validates :model, presence: true
  validates :pickup_location, presence: true
  validates :rental_instructions, presence: true
  # validates :start_date, presence: true
  # validates :end_date, presence: true
  # validates :postal_code, presence: true

  geocoded_by :pickup_location
  after_validation :geocode, if: :will_save_change_to_pickup_location?
  monetize :price_cents
end

app/controllers/cars_controller.rb
require 'json'
require 'pry-byebug'
require 'ostruct'

class CarsController < ApplicationController
  skip_before_action :authenticate_user!, only: :index
  before_action :set_car, only: [:show, :edit, :update, :destroy]

  def index

    # 1. Find me all cars that are within the booking timeframe
  
    start_date_search = params[:search][:start_date]
    end_date_search = params[:search][:end_date]
    sql = "select distinct on(license_plate) license_plate, * from cars join bookings on cars.id = bookings.car_id
    where (bookings.start_date > cast(case when '#{end_date_search}' = '' then null else '#{end_date_search}' end AS date)
    OR bookings.end_date < cast(case when '#{start_date_search}' = '' then null else '#{start_date_search}' end AS date))"

    # # 1. Find me all cars that are within the booking timeframe
    # sql = "select * from cars left join bookings on cars.id = bookings.car_id
    # where (bookings.start_date > cast('#{params[:search][:end_date]}' as date)
    # OR bookings.end_date < cast('#{params[:search][:start_date]}' as date))"
    
    results = ActiveRecord::Base.connection.execute(sql)

    # 2. Get cars address

    @cars = []
    results.each do |car|
      distance = Geocoder::Calculations.distance_between(car["pickup_location"], params[:search][:address])
      if distance < 10
        os = OpenStruct.new car
        @cars << os
      else
        next
      end
    end

    #map markers for cars
    @markers = @cars.map do |car|
      {
        lat: car.latitude,
        lng: car.longitude
      }
    end
  end

  def new
    @car = Car.new
  end

  def create
    @car = Car.new(car_params)
    @car.owner_id = current_user.id
    if @car.save
      redirect_to car_path(@car)
    else
      render :new
    end
  end

  def show
    @booking = Booking.new
    @favorite = Favorite.new
  end

  def edit
  end

  def update
    @car.update(car_params)
    redirect_to car_path(@car)
  end

  def destroy
    @car.destroy
    redirect_to cars_path
  end

  def favorite_new
    @favorite = Favorite.new
  end

  def favorite_save
    @favorite = Favorite.new(favorite_params)
    @favorite.save

    # no need for app/views/restaurants/create.html.erb
    redirect_to favorite_path(@favorite)
  end



  private

  def set_car
    @car = Car.find(params[:id])
  end

  def car_params
    params.require(:car).permit(:license_plate, :age, :model, :brand, :pickup_location, :rental_instructions, :image_urls)
  end

  def favorite_params
    params.require(:favorite).permit(:user_id, :car_id)
  end
end

app/views/cars/edit.html.erb
<div class="row">
  <div class="col-12 col-md-6 offset-lg-3">
    <div class="bg-white rounded p-3 shadow">
      <h3>Edit Car Details</h3>
      <%= simple_form_for @car do |f| %>
        <%= f.input :license_plate, placeholder: 'SUV-1234M' %>
        <%= f.input :brand %>
        <%= f.input :model %>
        <%= f.input :age %>
        <%= f.input :pickup_location %>
        <%= f.input :rental_instructions %>
        <%= f.input :image_urls, as: :file %>
        <%= f.submit class: 'btn btn-primary' %>
        <%= link_to 'Cancel', car_path, class: 'btn btn-danger ml-2' %>
      <% end %>
    </div>
  </div>
</div>

app/views/cars/index.html.erb
<h1 id="tag-title">We found <%= @cars.count %> great rental cars near you </h1>

<div class="row">


    <% @cars.each do |car| %>
      <div class="col-3">
        <div class="car-card">
          <div class="car-card-image" style="background-image: url('<%= car.image_urls %>')"></div>
          <div class="car-card-content">
            <div class="car-card-content-left">
              <p><%= car.brand %> | <%= Favorite.where(car_id: car.id).count %> Likes </p>
              <p id="license-plate">License: <%= car.license_plate %> </p>
            </div>
            <div class="car-card-content-right">
              <h4><%= humanized_money_with_symbol((car.price_cents/100).round)%>/day</h4>
            </div>
            <div class="car-type"><p><%= car.model %></p></div>
          </div>

          <div class="car-card-actions">
            <%= link_to 'View', car_path(car.car_id), class: 'btn btn-outline-secondary', id: 'viewbook' %>
            <%= link_to 'Book', car_path(car.car_id), class: 'btn btn-outline-secondary', id: 'viewbook' %>
  <!--
            <%= link_to 'Edit', edit_car_path(car), class: 'btn btn-success' %>
            <%= link_to "Remove", car_path(car),
                method: :delete,
                data: { confirm: "Are you sure you want to delete this list?" },
                class: 'btn btn-danger' %>
  -->
          </div>



        </div>
      </div>
    <% end %>


    <div id="map"
        style="width: 100%; height: 600px;"
        data-markers="<%= @markers.to_json %>"
        data-mapbox-api-key="<%= ENV["MAPBOX_API"] %>">
    </div>
</div>

app/views/cars/new.html.erb
<div class="row">
  <div class="col-12 col-md-6 offset-lg-3">
    <div class="bg-white rounded p-3 shadow">
      <h3>Add a new Car</h3>
      <%= simple_form_for @car do |f| %>
        <%= f.input :license_plate, placeholder: 'SUV-1234M' %>
        <%= f.input :brand %>
        <%= f.input :model %>
        <%= f.input :age %>
        <%= f.input :pickup_location %>
        <%= f.input :rental_instructions %>
        <%= f.input :image_urls, as: :file %>
        <%= f.submit class: 'btn btn-primary' %>
        <%= link_to 'Back', cars_path, class: 'btn btn-primary ml-2' %>
      <% end %>
    </div>
  </div>
</div>

app/views/cars/show.html.erb
<div class="map" style="background-image: url('<%= @car.image_urls %>')"></div>

<div class="row">
  <div class="col-8">
    <div class="car-show-card">
      <h4 class="car-card-title">Vehicle Details</h4>
      <span style="color:grey">
        <i class="fas fa-car"> </i>
      </span>
      Brand: <%= @car.brand %>
      <br>

      <span style="color:grey">
        <i class="fas fa-calendar-alt"> </i>
      </span>
      Manufacture: <%= 2021 - @car.age %>
      <br>

      <span style="color:grey">
        <i class="fas fa-map-marked"> </i>
      </span>
      Pickup Location: <%= @car.pickup_location %>
      <br>

      <span style="color:grey">
        <i class="fas fa-book-open"> </i>
      </span>
      Rental Instructions:
      <br>
      <%= @car.rental_instructions %>
      <br>

    </div>

   <div class="car-show-card">
     <h4 class="car-card-title"> Reviews </h4>
      <% @car.car_reviews.each do |car_review| %>
        <% if car_review.car_id == @car.id %>
          <p id="review-box">
            <%= car_review.review %>
            <%= car_review.created_at %>

          </p>
        <% end %>
      <% end %>
   </div>

  </div>

  <div class="col-4">
    <div class="car-show-card">
      <h4 class="car-card-title">Book your car</h5>

      <h2><%= humanized_money_with_symbol((@car.price_cents/100).round) %>/ day</h2>
      <%= simple_form_for [@car, @booking] do |f| %>
        <%= f.input :start_date, as: :datepicker %>
        <%= f.input :end_date, as: :datepicker %>
        <%= f.submit 'Book now', class: 'btn btn-secondary book', style: 'width:100%' %>
      <% end %>
    </div>

    <div class="car-show-card">
      <h4 class="car-card-title">Additional Options</h4>

      <%= link_to 'Leave a review', new_car_car_review_path(@car), class: "btn btn-outline-secondary", style: 'width:100%' %>
      <div id="bookmark">
        <% if @car.users_favorite.include? current_user%>
          <%= link_to "Liked", favorite_path(@car.id), method: :delete, class: "btn btn-secondary", style: 'width:100%' %>
        <%else%>
          <%= form_for(@favorite) do |f| %>
          <%= f.hidden_field :car_id, value: @car.id  %>
         <%= f.submit "Like", class: "btn btn-outline-secondary", style: 'width:100%'%>
        <%end%>
        <% end %>
      </div>

    </div>
    <div class="car-show-card">
        <h4 class="car-card-title">Share</h4>
          <i class="fab fa-facebook-square fa-2x"></i>
          <i class="fab fa-twitter-square fa-2x"></i>
          <i class="fab fa-pinterest-square fa-2x"></i>
          <i class="fas fa-envelope-square fa-2x"></i>

    </div>
  </div>
</div>



<br>


<!--
<%= link_to 'Edit', edit_car_path(@car), class: 'btn btn-outline-secondary' %>
<%= link_to 'Back', cars_path, class: 'btn btn-outline-secondary' %>

-->